// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/BookDetails/:id": {
    params: {
      "id": string;
    };
  };
  "/contact": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/price-match": {
    params: {};
  };
  "/shop": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/orders": {
    params: {};
  };
  "/order-confirmation": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/account" | "/BookDetails/:id" | "/contact" | "/login" | "/price-match" | "/shop" | "/signup" | "/cart" | "/checkout" | "/orders" | "/order-confirmation" | "/forgot-password";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/account.tsx": {
    id: "routes/account";
    page: "/account";
  };
  "routes/BookDetails.tsx": {
    id: "routes/BookDetails";
    page: "/BookDetails/:id";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/price-match.tsx": {
    id: "routes/price-match";
    page: "/price-match";
  };
  "routes/shop.tsx": {
    id: "routes/shop";
    page: "/shop";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/Cart.tsx": {
    id: "routes/Cart";
    page: "/cart";
  };
  "routes/Checkout.tsx": {
    id: "routes/Checkout";
    page: "/checkout";
  };
  "routes/OrderHistory.tsx": {
    id: "routes/OrderHistory";
    page: "/orders";
  };
  "routes/OrderConfirmation.tsx": {
    id: "routes/OrderConfirmation";
    page: "/order-confirmation";
  };
  "routes/forgotpassword.tsx": {
    id: "routes/forgotpassword";
    page: "/forgot-password";
  };
};